In [9]:
import os
print("Current Working Directory:")
print(os.getcwd())

import os

os.chdir(r"C:\Users\vinay kumar\OneDrive\Documents\vinay\ML learning\ML-LAB")

print(os.getcwd())
print(os.listdir("data"))


Current Working Directory:
C:\Users\vinay kumar\OneDrive\Documents\vinay\ML learning\simple-linear-regression
C:\Users\vinay kumar\OneDrive\Documents\vinay\ML learning\ML-LAB
['Iris.csv']


In [ ]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.feature_selection import SelectKBest, f_classif, SelectFromModel
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

# LOAD DATASET
data = load_iris()
X = data.data
y = data.target

# Convert to DataFrame
df = pd.DataFrame(X, columns=data.feature_names)

print("Original Data:\n", df.head())

Original Data:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


In [ ]:
#  FEATURE SCALING

# ---- Standardization ----
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)

print("\nStandardized Data:\n", X_standardized[:5])

# ---- Normalization ----
normalizer = MinMaxScaler()
X_normalized = normalizer.fit_transform(X)

print("\nNormalized Data:\n", X_normalized[:5])



Standardized Data:
 [[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]

Normalized Data:
 [[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


In [ ]:
# FEATURE SELECTION 

#  SelectKBest
# Select top 2 features based on ANOVA F-test
selector_kbest = SelectKBest(score_func=f_classif, k=2)
X_kbest = selector_kbest.fit_transform(X, y)

print("\nSelectKBest Features:\n", X_kbest[:5])

# ---- SelectFromModel ----
# Using Logistic Regression model
model = LogisticRegression(max_iter=200)
model.fit(X, y)

selector_model = SelectFromModel(model)
X_model = selector_model.fit_transform(X, y)

print("\nSelectFromModel Features:\n", X_model[:5])

# ---- Sequential Forward Selection ----
from sklearn.feature_selection import SequentialFeatureSelector

sfs = SequentialFeatureSelector(
    model,
    n_features_to_select=2,
    direction='forward'
)

sfs.fit(X, y)

# Get selected feature indices
selected_features = sfs.get_support(indices=True)

print("\nSequential Forward Selected Feature Index:", selected_features)

# Display selected feature names
print("Selected Feature Names:", df.columns[selected_features])


SelectKBest Features:
 [[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]]

SelectFromModel Features:
 [[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]]

Sequential Forward Selected Feature Index: [2 3]
Selected Feature Names: Index(['petal length (cm)', 'petal width (cm)'], dtype='str')
